name: Deploy

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: pip3 install -r requirements.txt

      - name: Run deployment script
        run: python3 .github/workflows/deploy.py
        env:
          dojo_username: ${{ secrets.dojo_username }}
          dojo_password: ${{ secrets.dojo_password }}