name: Deploy

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: upload-project
        uses: DojoCodes/DojoActions@v1
        with:
          dojo-username: "dojo"
          dojo-token: ${{ secrets.DOJO_TOKEN }}
